import Head from 'next/head';
import { Inter } from '@next/font/google';
import MainPage from '../components/MainPage';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Michael Kleyman Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MainPage />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
}
