import Head from 'next/head';
import { Inter } from '@next/font/google';
import MainPage from '../components/MainPage';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Michael Kleyman Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='theme-color' content='#fff' />
        <link rel='icon' href='/favicon.ico' />
        <link
          rel='apple-touch-icon'
          href='https://www.google.com/url?sa=i&url=https%3A%2F%2Fdepositphotos.com%2Fvector-images%2Flogo-k-mk.html&psig=AOvVaw3sLIDNtEjMmNreHyoZssU1&ust=1674064348270000&source=images&cd=vfe&ved=0CA8QjRxqFwoTCICVz-iVz_wCFQAAAAAdAAAAABAF'
        />
        <link rel='manifest' href='/manifest.json' />
      </Head>
      <MainPage />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
}
